name: fantasy_clock
description: Fantasy clock
version: 0.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.jpg
    - assets/images/colon.png
    - assets/images/digit1/1-1.png
    - assets/images/digit1/1-2.png
    - assets/images/digit2/2-1.png
    - assets/images/digit2/2-2.png
    - assets/images/digit2/2-3.png
    - assets/images/digit3/3-1.png
    - assets/images/digit3/3-2.png
    - assets/images/digit3/3-3.png
    - assets/images/digit4/4-1.png
    - assets/images/digit4/4-2.png
    - assets/images/digit4/4-3.png
